### PR TITLE
changed WSGI_APPLICATION as per issue 11

### PR DESCRIPTION
**Pull request by niallrobinson**
> I am open to pull requests.

Good - here you go. I have no idea what I'm doing and am a total django n00b, but it screwed me up and i just followed the directions on issue #11

### CODE REVIEW

**Comment by jfmatth** [comment]
Thanks for submitting, 

I'm gong to run some tests first and see what this does.  Honestly, your logic may not work, since the WGSI app I'm using when "ON PAAS" is not the one you listed.

Also, if you lookup the definition of this setting, it's only used by the runserver command by manage.py, so I"m thinking I'll just remove it all together.

Thanks,

John

**Comment by jfmatth** [comment]
Also, don't feel like a n00b, we all start somewhere, and thank goodness for Github that makes it easy.

J

**Comment by awwong1** [comment]
Haha, I should have made a pull request a while ago.

The WSGI_APPLICATION definition in the settings file is invalid, just delete the line.

'mysite.wsgi.application' throws an import error, always.

By default, it's set to None. In a development environment, this will resort to using Django's built in WSGI application. This allows you to use the `manage.py runserver` command.
https://docs.djangoproject.com/en/1.7/ref/settings/#wsgi-application

On Openshift, we explicitly define the WSGI Application using the environment variable.
https://developers.openshift.com/en/python-environment-variables.html
Having the WSGI_APPLICATION set while running on Openshift's PAAS won't effect anything. (Confirmed, as I made that change on my setup a while ago)

**Comment by niallrobinson** [comment]
Hi guys - just nuked the line altogether. I found both approaches did the trick when I tried on my machine.

**Comment by jfmatth** [comment]
Niall, thanks for confirming.  I'll try to get to the change this week.

J

**Pull request merged**
